[package]
name = "proto-test"
version = "0.1.0"
edition = "2024"

[dependencies]
aead = { version = "0.5.2", features = ["bytes", "std"] }
anyhow = "1.0.98"
bytes = "1.10.1"
chacha20poly1305 = "0.10.1"
ed25519-dalek = "2.1.1"
x25519-dalek = "2.0.1"
zeroize = "1.8.1"
